AGENT_PORT = 9899
SENDER_PORT = 9090
RECEIVER_PORT = 9091

AGENT_ADDRESS = ("localhost", AGENT_PORT)
SENDER_ADDRESS = ("localhost", SENDER_PORT)
RECEIVER_ADDRESS = ("localhost", RECEIVER_PORT)

DATA_SIZE = 1024
